#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: GPL-2.0-only
#

# We use `stack` only to install GHC and cabal-install, not to build the project.
# The rest of the build works via cabal

# Stackage LTS Haskell 19.12 (ghc-9.0.2)
resolver: lts-19.12

packages: []
extra-deps: []

flags: {}
extra-package-dbs: []
